---
- name: Login to OCP and Get  Project
  command: "{{ item }}"
  with_items:
    - "{{ OC_LOC}} login -u {{ OCP_USER }} -p {{OCP_PASS }}"
    - "{{OC_LOC}} project {{ GIT_SOURCE_PROJECT }}"

- name: Create Fuse Agency App
  shell: "{{ OC_LOC }} new-app {{FUSE_GIT_REPO}}  --image-stream=fis-java-openshift:2.0  --context-dir={{FUSE_GIT_REPO_CONTEXT}} --name={{FUSE_APP_NAME}} -l app={{FUSE_APP_NAME}}"

- name: patch service
  shell: "{{ OC_LOC }} get svc {{FUSE_APP_NAME}} -o json | {{SED_LOC}} -e 's/\"targetPort\": 8778/\"targetPort\": 8182/g' | {{OC_LOC}} replace svc {{FUSE_APP_NAME}} -f -"

- name: expose service
  shell: "{{ OC_LOC }} expose svc {{FUSE_APP_NAME}}"


